### ISSUE TITLE
Can’t debug .net projects

### ISSUE THREAD

**Issue by danyhoron** [ptr727/VSCode-Server-DotNetCore#16]
I installed this extension: `muhammad-sammy.csharp`

When I try to debug my app, I get this error:
```
Command 'Debug: Start Debugging' resulted in an error
Unexpected token u in JSON at position 0
```
I don’t know who generated it, I looked at all the outputs and couldn’t find why this happened.

**Comment by ptr727** [comment]
https://github.com/muhammadsammy/free-omnisharp-vscode/issues/60
