### ISSUE TITLE
Support for NET8, ARM64

### ISSUE THREAD

**Issue by petre-c** [ptr727/VSCode-Server-DotNetCore#17]
Hello, @ptr727 ,

Please add dotnet 8 support along with ARM64.

Alternatively, I could do that. Are you accepting merge requests?

Thanks!
- Petre

**Comment by ptr727** [comment]
Already supported, STS builds are .NET 8 and ARM64 is an existing target, how did you test?

**Comment by petre-c** [comment]
Hey, @ptr727 . I didn't test, sorry about that.

Merry Christmas and a happy new year.
