### ISSUE TITLE
Support for ARM64 platform

### ISSUE THREAD

**Issue by petrechitashvili** [ptr727/VSCode-Server-DotNetCore#9]
Greetings, @ptr727 !

Would you be willing to add ARM64 support to the image?

Thanks!
- Petre

**Comment by petrechitashvili** [comment]
Some context - I don't know if you have heard, but Oracle Cloud offers [Always Free ARM based instances](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm) with 4 OCPUs and 24GB or memory.

It would be nice to have an Always Free VSCode-Server with dotnet 🙂 

Have a good day!
- Petre

**Comment by ptr727** [comment]
Please try the develop tag, I added multi-arch support, `ptr727/vscode-server-dotnetcore:develop`.  
I only run x64, I have not yet tried your ARM cloud link.
